services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: rajmail-frontend

    ports:
      - "80:80"

    depends_on:
      - backend


  backend:
    build:
      context: ./backend

    container_name: rajmail-backend

    environment:

      DB_HOST: mysql

      DB_USER: root

      DB_PASSWORD: root

      DB_NAME: rajmail

      PORT: 5000

    ports:
      - "5000:5000"

    depends_on:
      - mysql


  mysql:
    image: mysql:8.0

    container_name: rajmail-mysql

    environment:

      MYSQL_ROOT_PASSWORD: root

      MYSQL_DATABASE: rajmail

    ports:
      - "3306:3306"

    volumes:

      - mysql-data:/var/lib/mysql

      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:

  mysql-data:
