sonar.projectKey=email-project
sonar.projectName=Email Project
sonar.projectVersion=1.0

sonar.sources=frontend,backend

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**

sonar.sourceEncoding=UTF-8
